# Generated by Django 5.0.3 on 2024-04-09 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('tenth_school', models.CharField(max_length=100)),
                ('tenth_year', models.CharField(max_length=100)),
                ('tenth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('twelfth_school', models.CharField(max_length=100)),
                ('twelfth_year', models.CharField(max_length=100)),
                ('twelfth_marks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('skill1', models.CharField(max_length=20)),
                ('skill2', models.CharField(max_length=20)),
                ('skill3', models.CharField(max_length=20)),
                ('interested_position', models.CharField(choices=[('position1', 'Software Engineer'), ('position2', 'Data Analyst'), ('position3', 'Data Engineer')], max_length=20)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
            ],
        ),
        migrations.CreateModel(
            name='Organizations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
